"""
letter_generator.py
--------------------
Builds a PDF letter to the road authority for a verified detection,
using reportlab. Fill in AUTHORITY_NAME / AUTHORITY_ADDRESS / SENDER_INFO
for your actual deployment, or load them from environment variables.
"""

import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

LETTERS_DIR = os.path.join(os.path.dirname(__file__), "letters")
UPLOADS_DIR = os.path.join(os.path.dirname(__file__), "uploads")
os.makedirs(LETTERS_DIR, exist_ok=True)

# ---- Configure these for your actual deployment ----
AUTHORITY_NAME = os.environ.get("AUTHORITY_NAME", "Public Works Department")
AUTHORITY_ADDRESS = os.environ.get("AUTHORITY_ADDRESS", "[Authority address here]")
SENDER_NAME = os.environ.get("SENDER_NAME", "SmartSurround Monitoring System")
SENDER_CONTACT = os.environ.get("SENDER_CONTACT", "[Your contact email]")
# -----------------------------------------------------


def _resolve_image(detection):
    """Locate the detection snapshot for the letter.

    Rows store the image as a BARE basename (app.py + a one-time migration
    normalize both / and \\ paths), so resolve it against UPLOADS_DIR. Legacy
    rows that still carry a full absolute path are handled as-is."""
    try:
        raw = (detection["image_path"] or "").strip()
    except (KeyError, IndexError):
        raw = ""
    if not raw:
        return None
    if os.path.isabs(raw) and os.path.exists(raw):
        return raw
    candidate = os.path.join(UPLOADS_DIR, os.path.basename(raw.replace("\\", "/")))
    return candidate if os.path.exists(candidate) else None


def generate_letter(detection) -> str:
    """
    detection: a sqlite3.Row (or dict-like) with keys:
        id, image_path, damage_class, confidence, severity, lat, lon,
        source, description, created_at
    Returns the path to the generated PDF.
    """
    filename = f"letter_detection_{detection['id']}.pdf"
    filepath = os.path.join(LETTERS_DIR, filename)

    doc = SimpleDocTemplate(filepath, pagesize=A4,
                             topMargin=2 * cm, bottomMargin=2 * cm,
                             leftMargin=2 * cm, rightMargin=2 * cm)
    styles = getSampleStyleSheet()
    story = []

    today = datetime.now().strftime("%d %B %Y")

    story.append(Paragraph(f"Date: {today}", styles["Normal"]))
    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph(f"To,<br/>{AUTHORITY_NAME}<br/>{AUTHORITY_ADDRESS}", styles["Normal"]))
    story.append(Spacer(1, 0.8 * cm))
    story.append(Paragraph("<b>Subject: Report of Damaged Road Condition Requiring Attention</b>",
                            styles["Heading3"]))
    story.append(Spacer(1, 0.4 * cm))

    lat = detection["lat"] if detection["lat"] is not None else "N/A"
    lon = detection["lon"] if detection["lon"] is not None else "N/A"
    source_label = "an automated roadside monitoring post" if detection["source"] == "esp32" \
        else "a citizen complaint submitted through the SmartSurround portal"

    body = f"""
    Dear Sir/Madam,<br/><br/>
    This is an automated notice generated by the SmartSurround monitoring system,
    following manual verification by a system administrator.<br/><br/>
    A road damage condition classified as <b>{detection['damage_class']}</b>
    (severity: <b>{detection['severity']}</b>, detection confidence:
    {round(detection['confidence'] * 100, 1) if detection['confidence'] is not None else 'N/A'}%)
    was identified via {source_label} at the following GPS coordinates:<br/><br/>
    <b>Latitude:</b> {lat} &nbsp;&nbsp; <b>Longitude:</b> {lon}<br/><br/>
    A verified snapshot of the affected location is attached below for reference.
    We request that the relevant maintenance team assess and address this condition
    at the earliest opportunity, particularly given the safety risk posed to
    vehicles and pedestrians.<br/><br/>
    """
    story.append(Paragraph(body, styles["Normal"]))

    if detection["description"]:
        story.append(Paragraph(f"<b>Reporter's note:</b> {detection['description']}",
                                styles["Normal"]))
        story.append(Spacer(1, 0.4 * cm))

    img_path = _resolve_image(detection)
    if img_path:
        try:
            story.append(Spacer(1, 0.3 * cm))
            story.append(RLImage(img_path, width=10 * cm, height=7.5 * cm))
        except Exception:
            pass

    story.append(Spacer(1, 0.8 * cm))
    story.append(Paragraph(f"Regards,<br/>{SENDER_NAME}<br/>{SENDER_CONTACT}", styles["Normal"]))

    doc.build(story)
    return filepath
