[env:esp32dev]

platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    adafruit/Adafruit BME680 Library @ ^2.0.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    mikalhart/TinyGPSPlus @ ^1.0.3
    bblanchon/ArduinoJson @ ^6.21.5
    mobizt/FirebaseClient @ ^2.2.13